spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/bootcamp_2508"
    username: "postgres"
    password: "admin1234"
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

# Base URL of data-provider app
data:
  provider:
    base-url: http://localhost:8081

# Polling rate (ms) for scheduled collector (optional)
stock:
  collector:
    rate-ms: 60000